# Generated by Django 6.0.3 on 2026-03-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('emergency', 'Emergency'), ('pharmacy', 'Pharmacy'), ('reception', 'Reception'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('ward', 'Ward'), ('outpatient', 'Outpatient')], max_length=100)),
                ('rating', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('patient_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
